###
POST http://localhost:8000/api/reserva HTTP/1.1
Content-Type: application/json

{
    "restaurante": "asd",
    "fecha": "qwe",
    "hora": "zxc",
    "cantidad": "eqw",
    "estado": "123"
}

### 
GET http://localhost:8000/api/reserva HTTP/1.1

//Busqueda por "_id"
###
GET http://localhost:8000/api/reserva/6463adcb3dbfede09d08f72e HTTP/1.1

//Actualiza por "_id"
###
PUT http://localhost:8000/api/reserva/6463adcb3dbfede09d08f72e HTTP/1.1
Content-Type: application/json

{
    "restaurante": "hola",
    "fecha": "qwe",
    "hora": "zxc",
    "cantidad": "eqw"
}

//Eliminar por "_id"
###
DELETE http://localhost:8000/api/reserva/6463aba1a36b01c350a5380d HTTP/1.1